# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: drewandre_development
  host: localhost
  pool: 5
  username:
  password:

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: drewandre_development_test
  host: localhost
  pool: 5
  username:
  password:

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: drewandre_production
  host: localhost
  pool: 5
  username:
  password:
